spring:
  profiles: 
  active: 

 spring:
  profiles: dev
  application: 
   name: microservicecloud-config-hua-dev

 spring:
  profiles: test
  application: 
   name: microservicecloud-config-hua-test