spring:
    profiles:
        active: dev
---
server:
  port: 8001
spring:
    profiles: dev
    application:
        name: microservicecloud-config-dept-client
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.72.129:3306/cloudDB01
        username: root
        password: root
        dbcp2:
          min-idle: 5
          initial-size: 5
          max-total: 5
          max-wait-millis: 200
mybatis:
  type-aliases-package: com.shu.springcloud.entity
  mapper-locations: classpath:mybatis/mapper/**/*.xml
eureka:
  client:
    service-url:
      defaultZone : http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/ #设置Eureka Server交互的地址查询服务和注册服务
  instance:
    instance-id: microservicecloud-dept8001 #自定义服务名称信息
    prefer-ip-address: true #访问路径可以显示IP地址
info:
  app.name: shu-microservicecloud
  company.name: www.shujinhao.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
  
  
---
server:
  port: 8001
spring:
    profiles: test
    application:
        name: microservicecloud-config-dept-client
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.72.129:3306/cloudDB02
        username: root
        password: root
        dbcp2:
          min-idle: 5
          initial-size: 5
          max-total: 5
          max-wait-millis: 200
mybatis:
  type-aliases-package: com.shu.springcloud.entity
  mapper-locations: classpath:mybatis/mapper/**/*.xml
eureka:
  client:
    service-url:
      defaultZone : http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/ #设置Eureka Server交互的地址查询服务和注册服务
  instance:
    instance-id: microservicecloud-dept8001 #自定义服务名称信息
    prefer-ip-address: true #访问路径可以显示IP地址
info:
  app.name: shu-microservicecloud
  company.name: www.shujinhao.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}